# ============================================================================
# GitLab CI/CD Stages
# Определение этапов pipeline для деплоя Corax на ALT Linux
# ============================================================================

stages:
  - config_generation    # Генерация конфигурационных файлов
  - node_preparation     # Подготовка деплой ноды
